import type { WCOrder } from "@/features/orders/types";

const billing = {
  first_name: "Ahmed",
  last_name: "Hassan",
  company: "",
  address_1: "15 Tahrir St",
  address_2: "",
  city: "Cairo",
  state: "C",
  postcode: "11511",
  country: "EG",
  email: "ahmed@example.com",
  phone: "+201000000000",
};

const shipping = {
  first_name: "Ahmed",
  last_name: "Hassan",
  company: "",
  address_1: "15 Tahrir St",
  address_2: "",
  city: "Cairo",
  state: "C",
  postcode: "11511",
  country: "EG",
};

export const mockOrders: WCOrder[] = [
  {
    id: 9001,
    status: "processing",
    date_created: "2025-03-01T09:00:00",
    total: "2499.00",
    subtotal: "2499.00",
    total_tax: "0.00",
    shipping_total: "0.00",
    currency: "EGP",
    line_items: [
      {
        id: 1,
        product_id: 102,
        name: "ساعة ذكية رياضية",
        quantity: 1,
        price: "2499",
        total: "2499.00",
        image: { src: "https://placehold.co/120x120?text=Watch" },
      },
    ],
    billing,
    shipping,
    payment_method: "cod",
    payment_method_title: "Cash on delivery",
    customer_note: "",
  },
  {
    id: 9002,
    status: "completed",
    date_created: "2025-03-02T11:30:00",
    total: "798.00",
    subtotal: "798.00",
    total_tax: "0.00",
    shipping_total: "0.00",
    currency: "EGP",
    line_items: [
      {
        id: 2,
        product_id: 201,
        name: "قميص قطن مصري",
        quantity: 2,
        price: "399",
        total: "798.00",
        image: { src: "https://placehold.co/120x120?text=Shirt" },
      },
    ],
    billing,
    shipping,
    payment_method: "cod",
    payment_method_title: "Cash on delivery",
    customer_note: "اتصلوا قبل التوصيل",
  },
  {
    id: 9003,
    status: "pending",
    date_created: "2025-03-03T16:45:00",
    total: "1899.00",
    subtotal: "1899.00",
    total_tax: "0.00",
    shipping_total: "0.00",
    currency: "EGP",
    line_items: [
      {
        id: 3,
        product_id: 301,
        name: "طقم أواني غير لاصقة",
        quantity: 1,
        price: "1899",
        total: "1899.00",
        image: { src: "https://placehold.co/120x120?text=Cookware" },
      },
    ],
    billing,
    shipping,
    payment_method: "cod",
    payment_method_title: "Cash on delivery",
    customer_note: "",
  },
];
