import type { WCProduct } from "./types";

// =====================================================
// 16 منتج حقيقي من sokany-eg.com
// الصور: sokany-eg.com/wp-content/uploads/...
// الأسعار: بالجنيه المصري (EGP)
// =====================================================

export const mockProducts: WCProduct[] = [
  // ─── BEST SELLERS ────────────────────────────────

  {
    id: 41214,
    name: "خلاط سوكاني 6000وات 2لتر بمطحنه موديل SK-999N",
    slug: "sk-999",
    permalink: "https://sokany-eg.com/product/sk-999/",
    date_created: "2023-06-15T10:00:00",
    date_modified: "2026-01-20T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>خلاط سوكانى SK-999N بقوة 6000 وات، سعة 2 لتر مع مطحنه إضافية. مثالي للاستخدام اليومي في المنزل. هيكل استنالس عالي الجودة، 5 سرعات مع وظيفة النبض.</p>",
    short_description: "<p>خلاط سوكانى قوي 6000وات مع مطحنه إضافية</p>",
    sku: "SK-999N",
    price: "2225",
    regular_price: "2225",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 854,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 45,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 101,
        src: "https://sokany-eg.com/wp-content/uploads/2026/01/ab012af1-2c30-4518-a8ec-51c4cc379536-800x800.jpg",
        name: "sk-999-1",
        alt: "خلاط سوكاني SK-999N",
      },
      {
        id: 102,
        src: "https://sokany-eg.com/wp-content/uploads/2026/01/ece76f84-9dbf-473b-b856-86e98e9e12f6-800x800.jpg",
        name: "sk-999-2",
        alt: "خلاط سوكاني SK-999N",
      },
    ],
    categories: [{ id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" }],
    tags: [{ id: 30, name: "خلاط", slug: "blender" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["6000 وات"] },
      { id: 2, name: "السعة", position: 1, visible: true, variation: false, options: ["2 لتر"] },
    ],
    average_rating: "4.8",
    rating_count: 127,
    meta_data: [],
  },

  {
    id: 39476,
    name: "SK-7033N كبه سوكانى استنالس 6.5لتر 1500وات",
    slug: "sk-7033",
    permalink: "https://sokany-eg.com/product/sk-7033/",
    date_created: "2023-04-10T10:00:00",
    date_modified: "2025-09-15T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>كبة سوكانى استنالس SK-7033N بسعة 6.5 لتر وقوة 1500 وات. مناسبة للعائلات الكبيرة. هيكل استنالس متين، 5 سرعات + وظيفة النبض.</p>",
    short_description: "<p>كبة سوكانى استنالس 6.5 لتر 1500 وات - منتج ساخن!</p>",
    sku: "SK-7033N",
    price: "2188",
    regular_price: "2188",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 1203,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 32,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 201,
        src: "https://sokany-eg.com/wp-content/uploads/2025/09/2569-2-800x800.jpg",
        name: "sk-7033-1",
        alt: "كبة سوكانى SK-7033N",
      },
    ],
    categories: [{ id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" }],
    tags: [{ id: 31, name: "كبة", slug: "food-processor" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1500 وات"] },
      { id: 2, name: "السعة", position: 1, visible: true, variation: false, options: ["6.5 لتر"] },
    ],
    average_rating: "4.9",
    rating_count: 248,
    meta_data: [],
  },

  {
    id: 39037,
    name: "SK-758-4N هاند بلندر استنالس 1000وات 4 في 1",
    slug: "sk-758-4",
    permalink: "https://sokany-eg.com/product/sk-758-4/",
    date_created: "2023-05-20T10:00:00",
    date_modified: "2026-01-10T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>هاند بلندر سوكانى استنالس SK-758-4N بقوة 1000 وات، 4 وظائف في 1. يشمل: خافق، مقطّع، خلاط، وكأس قياس. مثالي للمطابخ العصرية.</p>",
    short_description: "<p>هاند بلندر استنالس 1000 وات 4 في 1 من سوكانى</p>",
    sku: "SK-758-4N",
    price: "1750",
    regular_price: "1750",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 567,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 18,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 301,
        src: "https://sokany-eg.com/wp-content/uploads/2026/01/8af61943-86d7-4278-a5ee-e618b07d8fbd-800x800.jpg",
        name: "sk-758-4-1",
        alt: "هاند بلندر سوكانى SK-758-4N",
      },
    ],
    categories: [{ id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" }],
    tags: [{ id: 32, name: "هاند بلندر", slug: "hand-blender" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1000 وات"] },
    ],
    average_rating: "4.7",
    rating_count: 93,
    meta_data: [],
  },

  // ─── COFFEE SECTION ──────────────────────────────

  {
    id: 109195,
    name: "SK-04049 ماكينه قهوه اسبريسو 6 في 1 - 1.5لتر 1350وات 20بار",
    slug: "sk-04049",
    permalink: "https://sokany-eg.com/product/sk-04049/",
    date_created: "2026-03-01T10:00:00",
    date_modified: "2026-03-15T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>ماكينة قهوة اسبريسو سوكانى الاحترافية SK-04049 بـ 6 وظائف في 1، خزان 1.5 لتر، قوة 1350 وات، ضغط 20 بار للحصول على قهوة مثالية. تأتي مع رغوة اللبن، ومطحنة القهوة، وخيارات متعددة للمشروبات.</p>",
    short_description: "<p>ماكينة اسبريسو احترافية 6 في 1 بضغط 20 بار</p>",
    sku: "SK-04049",
    price: "32500",
    regular_price: "32500",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 89,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 8,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 401,
        src: "https://sokany-eg.com/wp-content/uploads/2026/03/e74776e4-cca8-4a3a-bb9c-76413fa89f33-800x800.jpg",
        name: "sk-04049-1",
        alt: "ماكينة قهوة سوكانى SK-04049",
      },
    ],
    categories: [
      { id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" },
      { id: 21, name: "مطحنه وماكينه قهوه", slug: "coffee-maker" },
    ],
    tags: [{ id: 33, name: "قهوة", slug: "coffee-maker" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1350 وات"] },
      { id: 3, name: "الضغط", position: 2, visible: true, variation: false, options: ["20 بار"] },
    ],
    average_rating: "5.0",
    rating_count: 34,
    meta_data: [],
  },

  {
    id: 78726,
    name: "SK-09049 ماكينه قهوه سوكانى ديجيتال 250مل 550وات",
    slug: "sk-09049",
    permalink: "https://sokany-eg.com/product/sk-09049/",
    date_created: "2025-07-10T10:00:00",
    date_modified: "2025-07-10T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "<p>ماكينة قهوة سوكانى ديجيتال SK-09049 للاستخدام المنزلي. خزان 250 مل، قوة 550 وات، شاشة ديجيتال واضحة، سهلة الاستخدام والتنظيف.</p>",
    short_description: "<p>ماكينة قهوة ديجيتال صغيرة ومتميزة من سوكانى</p>",
    sku: "SK-09049",
    price: "1625",
    regular_price: "1625",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 312,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 27,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 501,
        src: "https://sokany-eg.com/wp-content/uploads/2025/07/1f6438e1-b4ae-4ddc-a1ce-40652e2e9676-800x800.jpg",
        name: "sk-09049-1",
        alt: "ماكينة قهوة سوكانى SK-09049",
      },
    ],
    categories: [
      { id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" },
      { id: 21, name: "مطحنه وماكينه قهوه", slug: "coffee-maker" },
    ],
    tags: [{ id: 33, name: "قهوة", slug: "coffee-maker" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["550 وات"] },
    ],
    average_rating: "4.6",
    rating_count: 78,
    meta_data: [],
  },

  // ─── HAIR CARE ───────────────────────────────────

  {
    id: 37631,
    name: "SK-1934 فرشه استشوار سوكانى 1600وات",
    slug: "sk-1934",
    permalink: "https://sokany-eg.com/product/sk-1934/",
    date_created: "2023-01-15T10:00:00",
    date_modified: "2026-02-10T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>فرشة استشوار سوكانى SK-1934 بقوة 1600 وات. تعمل على تجفيف وتمشيط الشعر في آنٍ واحد. مناسبة لجميع أنواع الشعر. ذكية وسهلة الاستخدام.</p>",
    short_description: "<p>فرشة استشوار احترافية 1600 وات من سوكانى</p>",
    sku: "SK-1934",
    price: "1420",
    regular_price: "1420",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 1876,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 60,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 601,
        src: "https://sokany-eg.com/wp-content/uploads/2026/02/3484-800x800.jpg",
        name: "sk-1934-1",
        alt: "فرشة استشوار سوكانى SK-1934",
      },
    ],
    categories: [{ id: 19, name: "العناية الشخصية", slug: "personal-care" }],
    tags: [{ id: 34, name: "فرشة شعر", slug: "bruch" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1600 وات"] },
    ],
    average_rating: "4.8",
    rating_count: 445,
    meta_data: [],
  },

  {
    id: 37445,
    name: "SK-1914N فرشه استشوار سوكانى 1260وات",
    slug: "sk-1914",
    permalink: "https://sokany-eg.com/product/sk-1914/",
    date_created: "2023-01-10T10:00:00",
    date_modified: "2026-02-05T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "<p>فرشة استشوار سوكانى SK-1914N بقوة 1260 وات. خفيفة الوزن وسهلة الحمل. مناسبة للشعر الرفيع والمتوسط. تأتي مع ميزة الأيونات لحماية الشعر.</p>",
    short_description: "<p>فرشة استشوار خفيفة 1260 وات بتقنية الأيونات</p>",
    sku: "SK-1914N",
    price: "860",
    regular_price: "860",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 932,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 85,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 701,
        src: "https://sokany-eg.com/wp-content/uploads/2026/02/e82b7837-2c1a-4d1f-ab07-0f7c35565538-800x800.jpg",
        name: "sk-1914-1",
        alt: "فرشة استشوار سوكانى SK-1914N",
      },
    ],
    categories: [{ id: 19, name: "العناية الشخصية", slug: "personal-care" }],
    tags: [{ id: 34, name: "فرشة شعر", slug: "bruch" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1260 وات"] },
    ],
    average_rating: "4.6",
    rating_count: 213,
    meta_data: [],
  },

  {
    id: 109812,
    name: "SK-15053 استشوار سوكانى ديجيتال 1600وات",
    slug: "sk-15053",
    permalink: "https://sokany-eg.com/product/sk-15053/",
    date_created: "2026-03-10T10:00:00",
    date_modified: "2026-03-15T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>استشوار سوكانى ديجيتال SK-15053 بقوة 1600 وات. شاشة ديجيتال للتحكم في درجة الحرارة، 5 درجات حرارة مختلفة، مناسب لجميع أنواع الشعر.</p>",
    short_description: "<p>استشوار ديجيتال احترافي 1600 وات مع شاشة تحكم</p>",
    sku: "SK-15053",
    price: "2034",
    regular_price: "2034",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 156,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 22,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 801,
        src: "https://sokany-eg.com/wp-content/uploads/2026/03/c63ec576-f075-42d6-add6-c501f1eb16eb-800x800.jpg",
        name: "sk-15053-1",
        alt: "استشوار سوكانى SK-15053",
      },
    ],
    categories: [{ id: 19, name: "العناية الشخصية", slug: "personal-care" }],
    tags: [{ id: 35, name: "استشوار", slug: "hair-dryer" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1600 وات"] },
    ],
    average_rating: "4.9",
    rating_count: 44,
    meta_data: [],
  },

  // ─── ON SALE PRODUCTS ────────────────────────────

  {
    id: 87788,
    name: "SK-15049 فرشه استشوار بمشط سوكانى 2 في 1 1200وات",
    slug: "sk-15049",
    permalink: "https://sokany-eg.com/product/sk-15049/",
    date_created: "2025-10-01T10:00:00",
    date_modified: "2026-02-15T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "<p>فرشة استشوار سوكانى SK-15049 بتقنية 2 في 1 مع مشط مدمج. قوة 1200 وات، مناسبة لتمشيط وتجفيف الشعر في نفس الوقت. عرض خاص بخصم 15%.</p>",
    short_description: "<p>فرشة استشوار بمشط 2 في 1 - خصم 15%!</p>",
    sku: "SK-15049",
    price: "652",
    regular_price: "766",
    sale_price: "652",
    on_sale: true,
    purchasable: true,
    total_sales: 445,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 38,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 901,
        src: "https://sokany-eg.com/wp-content/uploads/2026/02/94db522e-d09a-4831-895c-e9836d5eacb1-800x800.jpg",
        name: "sk-15049-1",
        alt: "فرشة استشوار سوكانى SK-15049",
      },
    ],
    categories: [{ id: 19, name: "العناية الشخصية", slug: "personal-care" }],
    tags: [{ id: 34, name: "فرشة شعر", slug: "bruch" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1200 وات"] },
    ],
    average_rating: "4.7",
    rating_count: 128,
    meta_data: [],
  },

  {
    id: 74841,
    name: "SK-15043 فرشه شعر سوكانى مشط 1200وات",
    slug: "sk-15043",
    permalink: "https://sokany-eg.com/product/sk-15043/",
    date_created: "2025-05-01T10:00:00",
    date_modified: "2026-02-10T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "<p>فرشة شعر سوكانى SK-15043 بقوة 1200 وات مع مشط متكامل. خصم خاص 15%. مثالية للشعر الكثيف والمتوسط.</p>",
    short_description: "<p>فرشة شعر مشط 1200 وات - خصم 15%!</p>",
    sku: "SK-15043",
    price: "822",
    regular_price: "967",
    sale_price: "822",
    on_sale: true,
    purchasable: true,
    total_sales: 298,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 15,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 1001,
        src: "https://sokany-eg.com/wp-content/uploads/2026/02/4338fa80-f2d9-4db7-a937-15af14a69264-800x800.jpg",
        name: "sk-15043-1",
        alt: "فرشة شعر سوكانى SK-15043",
      },
    ],
    categories: [{ id: 19, name: "العناية الشخصية", slug: "personal-care" }],
    tags: [{ id: 34, name: "فرشة شعر", slug: "bruch" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1200 وات"] },
    ],
    average_rating: "4.5",
    rating_count: 89,
    meta_data: [],
  },

  // ─── AIR FRYERS ──────────────────────────────────

  {
    id: 109095,
    name: "SK-10118 قلايه سوكانى 7.5لتر 2000وات ديجيتال",
    slug: "sk-10118",
    permalink: "https://sokany-eg.com/product/sk-10118/",
    date_created: "2026-03-01T10:00:00",
    date_modified: "2026-03-10T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>قلاية هوائية سوكانى SK-10118 بسعة 7.5 لتر وقوة 2000 وات. شاشة ديجيتال تعمل باللمس، 8 برامج طهي مُسبقة، طبقة غير لاصقة عالية الجودة. مناسبة للعائلات الكبيرة.</p>",
    short_description: "<p>قلاية هوائية ديجيتال كبيرة 7.5 لتر من سوكانى</p>",
    sku: "SK-10118",
    price: "4000",
    regular_price: "4000",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 234,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 12,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 1101,
        src: "https://sokany-eg.com/wp-content/uploads/2026/03/b4e42e7d-873f-47ce-b531-7b2156484d2d-800x800.jpg",
        name: "sk-10118-1",
        alt: "قلاية هوائية سوكانى SK-10118",
      },
    ],
    categories: [{ id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" }],
    tags: [{ id: 36, name: "قلاية هوائية", slug: "airfrayer" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["2000 وات"] },
      { id: 2, name: "السعة", position: 1, visible: true, variation: false, options: ["7.5 لتر"] },
    ],
    average_rating: "4.9",
    rating_count: 67,
    meta_data: [],
  },

  {
    id: 89888,
    name: "SK-10094 قلايه سوكانى ديجيتال 14لتر 1800وات",
    slug: "sk-10094",
    permalink: "https://sokany-eg.com/product/sk-10094/",
    date_created: "2025-10-15T10:00:00",
    date_modified: "2026-02-01T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "<p>قلاية هوائية سوكانى SK-10094 بسعة ضخمة 14 لتر وقوة 1800 وات. مثالية للمطاعم والتجمعات الكبيرة. شاشة ديجيتال، 10 برامج طهي تلقائية.</p>",
    short_description: "<p>قلاية هوائية عملاقة 14 لتر للعائلات الكبيرة</p>",
    sku: "SK-10094",
    price: "6375",
    regular_price: "6375",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 89,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 6,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 1201,
        src: "https://sokany-eg.com/wp-content/uploads/2026/02/43e78432-73e4-4c5c-a17c-aba756f4db26-800x800.jpg",
        name: "sk-10094-1",
        alt: "قلاية هوائية سوكانى SK-10094",
      },
    ],
    categories: [{ id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" }],
    tags: [{ id: 36, name: "قلاية هوائية", slug: "airfrayer" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1800 وات"] },
      { id: 2, name: "السعة", position: 1, visible: true, variation: false, options: ["14 لتر"] },
    ],
    average_rating: "4.7",
    rating_count: 31,
    meta_data: [],
  },

  // ─── HAIR STRAIGHTENERS ──────────────────────────

  {
    id: 119921,
    name: "SK-15026 مكواه شعر سوكانى ديجيتال بالبخار",
    slug: "sk-15026",
    permalink: "https://sokany-eg.com/product/sk-15026/",
    date_created: "2026-04-01T10:00:00",
    date_modified: "2026-04-01T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>مكواة شعر سوكانى ديجيتال بالبخار SK-15026. شاشة ديجيتال، تقنية البخار لترطيب الشعر أثناء الفرد، ألواح تيتانيوم عالية الجودة. تسخين سريع في 15 ثانية.</p>",
    short_description: "<p>مكواة شعر بالبخار مع شاشة ديجيتال - جديدة</p>",
    sku: "SK-15026",
    price: "1934",
    regular_price: "1934",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 45,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 30,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 1301,
        src: "https://sokany-eg.com/wp-content/uploads/2026/04/7a6ec95d-a88a-461b-b8e8-4304bfe78739-800x800.jpg",
        name: "sk-15026-1",
        alt: "مكواة شعر سوكانى SK-15026",
      },
    ],
    categories: [{ id: 19, name: "العناية الشخصية", slug: "personal-care" }],
    tags: [{ id: 37, name: "مكواة شعر", slug: "hair-straighteners" }],
    attributes: [
      { id: 4, name: "النوع", position: 0, visible: true, variation: false, options: ["بالبخار", "ديجيتال"] },
    ],
    average_rating: "5.0",
    rating_count: 12,
    meta_data: [],
  },

  {
    id: 43453,
    name: "SK-201A مضرب نسكافيه شحن سوكانى",
    slug: "sk-201a",
    permalink: "https://sokany-eg.com/product/201a/",
    date_created: "2023-07-01T10:00:00",
    date_modified: "2025-11-01T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "<p>مضرب نسكافيه سوكانى SK-201A يعمل بالشحن. خفيف الوزن ومريح، مناسب للاستخدام في أي مكان. بطارية قابلة للشحن عبر USB، يدوم حتى 60 دقيقة.</p>",
    short_description: "<p>مضرب نسكافيه شحن USB أنيق وعملي من سوكانى</p>",
    sku: "SK-201A",
    price: "350",
    regular_price: "350",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 2340,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 150,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 1401,
        src: "https://sokany-eg.com/wp-content/uploads/2024/05/3306-800x800.jpg",
        name: "sk-201a-1",
        alt: "مضرب نسكافيه سوكانى SK-201A",
      },
    ],
    categories: [
      { id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" },
      { id: 21, name: "مطحنه وماكينه قهوه", slug: "coffee-maker" },
    ],
    tags: [{ id: 38, name: "مضرب قهوة", slug: "egg-mixer" }],
    attributes: [
      { id: 5, name: "نوع الشحن", position: 0, visible: true, variation: false, options: ["USB"] },
    ],
    average_rating: "4.9",
    rating_count: 876,
    meta_data: [],
  },

  {
    id: 95786,
    name: "SK-7099A كبه سوكانى استنالس 8لتر 1800وات + قطعة سلاح",
    slug: "sk-7099a",
    permalink: "https://sokany-eg.com/product/sk-7099a/",
    date_created: "2025-12-01T10:00:00",
    date_modified: "2026-01-05T10:00:00",
    type: "simple",
    status: "publish",
    featured: false,
    catalog_visibility: "visible",
    description: "<p>كبة سوكانى الاستنالس الكبيرة SK-7099A بسعة 8 لتر وقوة 1800 وات، تأتي مع قطعة سلاح إضافية. مثالية للعائلات الكبيرة. 5 سرعات، هيكل استنالس متين.</p>",
    short_description: "<p>كبة سوكانى 8 لتر استنالس مع قطعة سلاح</p>",
    sku: "SK-7099A",
    price: "2625",
    regular_price: "2625",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 167,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 0,
    stock_status: "outofstock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 1501,
        src: "https://sokany-eg.com/wp-content/uploads/2025/12/50a2b1a4-296d-4043-85c0-af67132ab724-800x800.jpg",
        name: "sk-7099a-1",
        alt: "كبة سوكانى SK-7099A",
      },
    ],
    categories: [{ id: 17, name: "أجهزة مطبخ", slug: "kitchen-supplies" }],
    tags: [{ id: 31, name: "كبة", slug: "food-processor" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1800 وات"] },
      { id: 2, name: "السعة", position: 1, visible: true, variation: false, options: ["8 لتر"] },
    ],
    average_rating: "4.8",
    rating_count: 52,
    meta_data: [],
  },
  {
    id: 66584,
    name: "SK-15030N طقم استشوار دوار سوكانى 4 في 1 1400وات",
    slug: "sk-15030",
    permalink: "https://sokany-eg.com/product/sk-15030/",
    date_created: "2025-01-10T10:00:00",
    date_modified: "2025-05-20T10:00:00",
    type: "simple",
    status: "publish",
    featured: true,
    catalog_visibility: "visible",
    description: "<p>طقم استشوار دوار سوكانى SK-15030N بقوة 1400 وات، 4 في 1. يشمل: فوطة تجفيف، رأس كيرلي، رأس تجعيد، ورأس تنعيم. يتميز بالرأس الدوار لسهولة التشكيل.</p>",
    short_description: "<p>طقم استشوار دوار متكامل 4 في 1 من سوكانى</p>",
    sku: "SK-15030N",
    price: "1700",
    regular_price: "1700",
    sale_price: "",
    on_sale: false,
    purchasable: true,
    total_sales: 789,
    virtual: false,
    downloadable: false,
    manage_stock: true,
    stock_quantity: 25,
    stock_status: "instock",
    backorders: "no",
    backorders_allowed: false,
    backordered: false,
    images: [
      {
        id: 1601,
        src: "https://sokany-eg.com/wp-content/uploads/2025/01/6060-1-800x800.jpg",
        name: "sk-15030-1",
        alt: "طقم استشوار سوكانى SK-15030N",
      },
    ],
    categories: [{ id: 19, name: "العناية الشخصية", slug: "personal-care" }],
    tags: [{ id: 34, name: "فرشة شعر", slug: "bruch" }],
    attributes: [
      { id: 1, name: "القوة", position: 0, visible: true, variation: false, options: ["1400 وات"] },
    ],
    average_rating: "4.7",
    rating_count: 189,
    meta_data: [],
  },
];

export type MockProductFilter = {
  category?: string | number;
  featured?: boolean;
  on_sale?: boolean;
  search?: string;
};

function applyMockProductFilters(
  params?: MockProductFilter,
): WCProduct[] {
  let results = [...mockProducts];

  if (params?.category) {
    results = results.filter((p) =>
      p.categories.some(
        (c) => c.id === Number(params.category) || c.slug === params.category,
      ),
    );
  }

  if (params?.featured) {
    results = results.filter((p) => p.featured);
  }

  if (params?.on_sale) {
    results = results.filter((p) => p.on_sale);
  }

  if (params?.search) {
    const q = params.search.toLowerCase();
    results = results.filter(
      (p) =>
        p.name.toLowerCase().includes(q) ||
        p.sku.toLowerCase().includes(q),
    );
  }

  return results;
}

/** محاكاة filtering + pagination */
export function filterMockProducts(
  params?: MockProductFilter & { per_page?: number; page?: number },
): WCProduct[] {
  const results = applyMockProductFilters(params);
  const page = params?.page ?? 1;
  const per_page = params?.per_page ?? 12;
  const start = (page - 1) * per_page;
  return results.slice(start, start + per_page);
}

export function listMockProductsMatching(
  params?: MockProductFilter,
): WCProduct[] {
  return applyMockProductFilters(params);
}
