import type { WCReview } from "@/features/reviews/types";

export const mockReviews: WCReview[] = [
  {
    id: 7001,
    product_id: 41214,
    status: "approved",
    reviewer: "Mona",
    reviewer_email: "mona@example.com",
    review: "<p>قوة ممتازة ونتيجة الخلط ثابتة حتى مع الاستخدام اليومي.</p>",
    rating: 5,
    verified: true,
    date_created: "2025-02-01T08:00:00",
  },
  {
    id: 7002,
    product_id: 41214,
    status: "approved",
    reviewer: "Karim",
    reviewer_email: "karim@example.com",
    review: "<p>الخامات جيدة جداً والمطحنة الإضافية مفيدة فعلاً.</p>",
    rating: 4,
    verified: false,
    date_created: "2025-02-02T08:00:00",
  },
  {
    id: 7003,
    product_id: 39476,
    status: "approved",
    reviewer: "Salma",
    reviewer_email: "salma@example.com",
    review: "<p>السعة كبيرة ومناسبة للعائلة، والأداء ثابت مع الكميات الكبيرة.</p>",
    rating: 5,
    verified: true,
    date_created: "2025-02-03T08:00:00",
  },
  {
    id: 7004,
    product_id: 39037,
    status: "approved",
    reviewer: "Omar",
    reviewer_email: "omar@example.com",
    review: "<p>ممتاز للتحضير السريع وسهل التنظيف بعد الاستخدام.</p>",
    rating: 4,
    verified: false,
    date_created: "2025-02-04T08:00:00",
  },
  {
    id: 7005,
    product_id: 109195,
    status: "approved",
    reviewer: "Dina",
    reviewer_email: "dina@example.com",
    review: "<p>ماكينة قوية جداً واستخراج الإسبريسو ممتاز بالنسبة للفئة السعرية.</p>",
    rating: 5,
    verified: true,
    date_created: "2025-02-05T08:00:00",
  },
];
