import type { WCCategory } from "./types";

export const mockCategories: WCCategory[] = [
  {
    id: 17,
    name: "أجهزة مطبخ",
    slug: "kitchen-supplies",
    description: "تشكيلة واسعة من أجهزة المطبخ الكهربائية سوكانى",
    display: "default",
    image: {
      id: 1,
      src: "https://sokany-eg.com/wp-content/uploads/2025/10/icons8-kitchen-room-100.png",
      alt: "أجهزة مطبخ",
    },
    parent: 0,
    count: 215,
    _links: {},
  },
  {
    id: 18,
    name: "أجهزة منزلية",
    slug: "home-appliances",
    description: "مكانس كهربائية، مكاوي بخار، ومراوح من سوكانى",
    display: "default",
    image: {
      id: 2,
      src: "https://sokany-eg.com/wp-content/uploads/2025/10/منزليه.png",
      alt: "أجهزة منزلية",
    },
    parent: 0,
    count: 98,
    _links: {},
  },
  {
    id: 19,
    name: "العناية الشخصية",
    slug: "personal-care",
    description: "فرد شعر، استشوارات، ومكاوي شعر من سوكانى",
    display: "default",
    image: {
      id: 3,
      src: "https://sokany-eg.com/wp-content/uploads/2026/04/88cdc891-f0c5-42ef-925d-94d0a17109e6.jpg",
      alt: "العناية الشخصية",
    },
    parent: 0,
    count: 120,
    _links: {},
  },
  {
    id: 20,
    name: "مكاوي بخار",
    slug: "cloth-iron",
    description: "مكاوي البخار الكهربائية من سوكانى",
    display: "default",
    image: {
      id: 4,
      src: "https://sokany-eg.com/wp-content/uploads/2025/12/مكوي-800x800.png",
      alt: "مكاوي بخار",
    },
    parent: 0,
    count: 50,
    _links: {},
  },
  {
    id: 21,
    name: "مطحنه وماكينه قهوه",
    slug: "coffee-maker",
    description: "ماكينات قهوة اسبريسو ومطاحن من سوكانى",
    display: "default",
    image: {
      id: 5,
      src: "https://sokany-eg.com/wp-content/uploads/2025/12/مكن-قهوة-800x800.png",
      alt: "مطحنه وماكينه قهوه",
    },
    parent: 17,
    count: 26,
    _links: {},
  },
  {
    id: 22,
    name: "قطع غيار",
    slug: "spare-parts",
    description: "قطع غيار أصلية لمنتجات سوكانى",
    display: "default",
    image: {
      id: 6,
      src: "https://sokany-eg.com/wp-content/uploads/2025/10/قطع-غيار1.png",
      alt: "قطع غيار",
    },
    parent: 0,
    count: 15,
    _links: {},
  },
];
